# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb25203ac35156bc6c1e02778a800679"
name = "customhouse-app"
application_url = "https://custom-house.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/collections/delete"
  topics = ["collections/delete"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = ["products/delete"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/create"
  topics = ["customers/create"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/update"
  topics = ["customers/update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = ["orders/create"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = ["orders/paid"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds/create"
  topics = ["refunds/create"]

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_metaobjects,write_metaobjects,write_metaobject_definitions,read_files,write_files,read_publications,write_publications,read_orders"

[auth]
redirect_urls = [
  "https://custom-house.onrender.com/api/auth"
]

[app_proxy]
url = "https://custom-house.onrender.com/proxy"
subpath = "customhouse"
prefix = "apps"
