query CartValidationsGenerateRunInput {
  cart {
    lines {
      id
      quantity
      creatorProductIdAttribute: attribute(key: "_creator_product_id") {
        value
      }
      feeKeyAttribute: attribute(key: "_customhouse_fee_key") {
        value
      }
      parentProductIdAttribute: attribute(key: "_customhouse_parent_product_id") {
        value
      }
      publicCartValidationAttribute: attribute(key: "_customhouse_public_cart_validation") {
        value
      }
      nonReturnAcknowledgement: attribute(key: "Customized product acknowledgement") {
        value
      }
      hiddenNonReturnAcknowledgement: attribute(key: "_customhouse_non_return_acknowledgement") {
        value
      }
      termsAcknowledgement: attribute(key: "Terms & Conditions") {
        value
      }
      hiddenTermsAcknowledgement: attribute(key: "_customhouse_terms_acknowledgement") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
            productOrigin: metafield(namespace: "customhouse", key: "product_origin") {
              value
            }
            designMode: metafield(namespace: "customhouse", key: "design_mode") {
              value
            }
            productType: metafield(namespace: "customhouse", key: "product_type") {
              value
            }
            creatorProductId: metafield(namespace: "customhouse", key: "creator_product_id") {
              value
            }
            creatorCartValidation: metafield(namespace: "customhouse", key: "creator_cart_validation") {
              jsonValue
            }
            productionMethodPricing: metafield(namespace: "customhouse", key: "production_method_pricing") {
              jsonValue
            }
          }
        }
      }
    }
  }
}
